
const localVisualPalette = {
  "Վիտամիններ և դեղեր": {
    background: "#ecfdf5",
    primary: "#0f766e",
    accent: "#fb923c",
    glyph: "+",
  },
  Հարդեղագործական: {
    background: "#fff7ed",
    primary: "#ea580c",
    accent: "#0f766e",
    glyph: "✦",
  },
  Աքսեսուարներ: {
    background: "#eff6ff",
    primary: "#2563eb",
    accent: "#fb923c",
    glyph: "✚",
  },
};

function localProductVisual(category) {
  const palette =
    localVisualPalette[category] || localVisualPalette["Վիտամիններ և դեղեր"];
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 320" role="img" aria-label="Nova Pharm local catalog illustration"><rect width="320" height="320" rx="36" fill="${palette.background}"/><circle cx="256" cy="58" r="72" fill="${palette.accent}" opacity=".16"/><circle cx="64" cy="274" r="88" fill="${palette.primary}" opacity=".08"/><rect x="87" y="54" width="146" height="212" rx="20" fill="white" stroke="${palette.primary}" stroke-width="8"/><rect x="107" y="78" width="106" height="34" rx="12" fill="${palette.primary}"/><text x="160" y="101" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" font-weight="700" fill="white">NOVA</text><circle cx="160" cy="167" r="43" fill="${palette.accent}"/><text x="160" y="188" text-anchor="middle" font-family="Arial, sans-serif" font-size="62" font-weight="700" fill="white">${palette.glyph}</text><rect x="112" y="226" width="96" height="12" rx="6" fill="${palette.primary}" opacity=".22"/></svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

const localCatalog = [
  [
    1,
    "Վիտամին D3 1000 ՄՄ, 60 հատ",
    "Витамин D3 1000 МЕ, 60 таблеток",
    "Vitamin D3 1000 IU, 60 tabs",
    "Վիտամիններ և դեղեր",
    4500,
    "60 հատ",
  ],
  [
    2,
    "Մուլտիվիտամինային համալիր, 60 հատ",
    "Мультивитаминный комплекс, 60 таблеток",
    "Multivitamin Complex, 60 tabs",
    "Վիտամիններ և դեղեր",
    3800,
    "60 հատ",
  ],
  [
    3,
    "Օմեգա-3 ձկան յուղ, 100 կապսուլ",
    "Омега-3 Рыбий жир, 100 капсул",
    "Omega-3 Fish Oil, 100 softgels",
    "Վիտամիններ և դեղեր",
    6500,
    "100 կապսուլ",
  ],
  [
    4,
    "Մագնեզիում B6, 50 հատ",
    "Магний B6, 50 таблеток",
    "Magnesium B6, 50 tabs",
    "Վիտամիններ և դեղեր",
    4900,
    "50 հատ",
  ],
  [
    5,
    "Իբուպրոֆեն 200 մգ, 20 հատ",
    "Ибупрофен 200 мг, 20 таблеток",
    "Ibuprofen 200 mg, 20 tabs",
    "Վիտամիններ և դեղեր",
    1800,
    "20 հատ",
  ],
  [
    6,
    "Պարացետամոլ 500 մգ, 20 հատ",
    "Парацетамол 500 мг, 20 таблеток",
    "Paracetamol 500 mg, 20 tabs",
    "Վիտամիններ և դեղեր",
    1200,
    "20 հատ",
  ],
  [
    7,
    "Նիմեսիլ, 9 պարկուճ",
    "Нимесил, 9 пакетиков",
    "Nimesil powder sachets, 9 pcs",
    "Վիտամիններ և դեղեր",
    2900,
    "9 հատ",
  ],
  [
    8,
    "Թերաֆլյու, 10 պարկուճ",
    "Терафлю, 10 пакетиков",
    "Theraflu powder sachets, 10 pcs",
    "Վիտամիններ և դեղեր",
    4500,
    "10 հատ",
  ],
  [
    9,
    "Ստոդալ հազի օշարակ, 200 մլ",
    "Стодаль сироп от кашля, 200 мл",
    "Stodal cough syrup, 200 ml",
    "Վիտամիններ և դեղեր",
    3600,
    "200 մլ",
  ],
  [
    10,
    "Օտրիվին քթի կաթիլներ, 10 մլ",
    "Отривин капли для носа, 10 мл",
    "Otrivin nasal drops, 10 ml",
    "Վիտամիններ և դեղեր",
    2400,
    "10 մլ",
  ],
  [
    11,
    "Ասպիրին Կարդիո 100 մգ, 30 հատ",
    "Аспирин Кардио 100 мг, 30 таблеток",
    "Aspirin Cardio 100 mg, 30 tabs",
    "Վիտամիններ և դեղեր",
    2600,
    "30 հատ",
  ],
  [
    12,
    "Նիտրոգլիցերին 0.5 մգ, 40 հատ",
    "Нитрогlycerin 0,5 мг, 40 таблеток",
    "Nitroglycerin 0.5 mg, 40 tabs",
    "Վիտամիններ և դեղեր",
    1500,
    "40 հատ",
  ],
  [
    13,
    "Օմեպրազոլ 20 մգ, 28 կապսուլ",
    "Омепразол 20 мг, 28 капсул",
    "Omeprazole 20 mg, 28 caps",
    "Վիտամիններ և դեղեր",
    3200,
    "28 կապսուլ",
  ],
  [
    14,
    "Մեզիմ Ֆորտե, 20 հատ",
    "Мезим Форте, 20 таблеток",
    "Mezym Forte, 20 tabs",
    "Վիտամիններ և դեղեր",
    2800,
    "20 հատ",
  ],
  [
    15,
    "Սմեկտա, 10 պարկուճ",
    "Смекта, 10 пакетиков",
    "Smecta powder sachets, 10 pcs",
    "Վիտամիններ և դեղեր",
    2500,
    "10 հատ",
  ],
  [
    16,
    "Դ-Պանտենոլ քսուք, 30 գ",
    "Д-Пантенол мазь, 30 г",
    "D-Panthenol ointment, 30 g",
    "Հարդեղագործական",
    3100,
    "30 գ",
  ],
  [
    17,
    "Արևապաշտպան SPF50 քսուք, 50 մլ",
    "Солнцезащитный крем SPF50, 50 мл",
    "Sunscreen SPF50 cream, 50 ml",
    "Հարդեղագործական",
    5400,
    "50 մլ",
  ],
  [
    18,
    "Ստերիլ վիրակապ, 5 հատ",
    "Стерильная повязка, 5 штук",
    "Sterile dressing, pack of 5",
    "Աքսեսուարներ",
    800,
    "5 հատ",
  ],
  [
    19,
    "Քլորհեքսիդին 0.05%, 100 մլ",
    "Хлоргексидин 0,05%, 100 мл",
    "Chlorhexidine 0.05%, 100 ml",
    "Հարդեղագործական",
    900,
    "100 մլ",
  ],
].map(([id, nameHy, nameRu, nameEn, category, price, unit]) => ({
  id,
  sku: `LOCAL-${id}`,
  nameHy,
  nameRu,
  nameEn,
  descriptionHy: null,
  descriptionRu: null,
  descriptionEn: null,
  category,
  price,
  unit,
  image: localProductVisual(category),
  rx: 0,
  outOfStock: 0,
  archived: 0,
  sortOrder: id,
}));

export { localCatalog };
